name = "kotlin-sync"
title = "Kotlin Sync Driver"

intersphinx = [ "https://www.mongodb.com/docs/manual/objects.inv",
                "https://www.mongodb.com/docs/drivers/objects.inv",
                "https://www.mongodb.com/docs/atlas/objects.inv"
              ]

toc_landing_pages = []

[constants]
driver-long = "MongoDB Kotlin Sync Driver"
driver-short = "Kotlin Sync Driver"
language = "Kotlin"
version-number = "5.1"
version = "v{+version-number+}"